### ISSUE TITLE
errors of binary genotype

### ISSUE THREAD

**Issue by computingmachine** [dapogon/cellcoal#1]
Hi Dr Posada,

How are the errors added to binary data? For example, I would like to simulate binary data with specified false positive rate 0.1 (G0.1 0.01) and false negative rate 0.01 (-D 0.01). I used the code below but it does not work

bin/cellcoal-1.1.0 -n10 -s10 -l10 -e10000 -g1.0e-04 -k0 -i1 -b0 -j10 -p0.0 -m0 G0.1 0.01 -D 0.01 -1 -2 -3 -4 -5 -6 -9 -v -x -#200011

**Comment by dapogon** [comment]
Hi,

There was an error in the parsing of -G that prevented its proper used. I fixed and put a new release 1.1.1. 

In any case, please note that your command line had a few glitches:
 
 "G0.1 0.01" should be "-G0.1 0.01", and 
"-D 0.01" should be "-D0.01"

Error generation is explained in the documentation.  Best, D
