### ISSUE TITLE
Distribution of coalescent time

### ISSUE THREAD

**Issue by bowliang** [dapogon/cellcoal#4]
Trying to simulate Coalescent genealogy with SH91 model implemented in CellCoal, but still feel confused about the distribution of the node times/root times after reading the reference paper, is there any explanation for this, like formula?

**Comment by dapogon** [comment]
The time to coalescence is:

```
tCA = log [e^gt + 2Ng  exp (k(k-1)/2)] / g  – t
```
where *g* is the exponential growth rate and *t* is the current time.
