### ISSUE TITLE
birthRate/deathRate typo

### ISSUE THREAD

**Issue by chifman** [dapogon/cellcoal#5]
on line 8611 there is a typo it should be if (birthRate<deathRate) then print the error

`if (deathRate < birthRate)
					{
					fprintf (stderr, "\n!!! PARAMETER ERROR: Bad death rate (%f), it should be smaller than the birth rate (%f)\n\n", deathRate, birthRate);
					PrintUsage(stderr);
					}`

**Comment by dapogon** [comment]
indeed, thx!
